CREATE OR REPLACE VIEW lastbought (releaseddate) AS
SELECT CASE WHEN NOT (SELECT COUNT ('X') FROM SALE_LINE WHERE e_mail = (SELECT USER FROM DUAL)) >=1
THEN sysdate 
ELSE (SELECT rel_date FROM (SELECT isvn, rel_date, order_s FROM DISCS JOIN SALE_LINE USING(ISVN) 
WHERE e_mail = (SELECT USER FROM DUAL) 
AND order_s = (SELECT * FROM (SELECT order_s FROM SALE_LINE WHERE e_mail = (SELECT USER FROM DUAL) ORDER BY order_s DESC) 
WHERE ROWNUM=1)
ORDER BY rel_date DESC) WHERE ROWNUM <=1) 
end AS rel_date 
FROM CLIENTS WHERE e_mail = (SELECT USER FROM DUAL);

CREATE OR REPLACE VIEW recommendations (ISVN, rec_dates) AS
SELECT * FROM (SELECT DISCS.ISVN, rel_date FROM DISCS JOIN lastbought ON DISCS.rel_date<=lastbought.releaseddate ORDER BY rel_date DESC) WHERE ROWNUM <=5;

CREATE OR REPLACE VIEW client_myself AS
SELECT * FROM CLIENTS WHERE email = (SELECT USER FROM DUAL);

CREATE ROLE CLIENTES;
REVOKE ALL ON MAKERS FROM CLIENTES;
REVOKE ALL ON MANAGERS FROM CLIENTES;
REVOKE ALL ON PUBLISHERS FROM CLIENTES;
REVOKE ALL ON STUDIOS FROM CLIENTES;
REVOKE ALL ON ARTISTS FROM CLIENTES;
REVOKE ALL ON MEMBERS FROM CLIENTES;
REVOKE ALL ON DISCS FROM CLIENTES;
REVOKE ALL ON SONGS FROM CLIENTES;
REVOKE ALL ON TRACKS FROM CLIENTES;
REVOKE ALL ON ALBUMS FROM CLIENTES;
REVOKE ALL ON SINGLES FROM CLIENTES;
REVOKE ALL ON RANKINGS FROM CLIENTES;
REVOKE ALL ON SLEVEES FROM CLIENTES;
REVOKE ALL ON RADIOS FROM CLIENTES;
REVOKE ALL ON PLAYBACKS FROM CLIENTES;
REVOKE ALL ON CLIENTS FROM CLIENTES;
REVOKE ALL ON SALE_LINE FROM CLIENTES;
REVOKE ALL ON lastbought FROM CLIENTES;

GRANT SELECT ON recommendations TO CLIENTES;
GRANT SELECT, UPDATE ON client_myself TO CLIENTES;
