DROP TABLE ARTISTAS CASCADE CONSTRAINT;
DROP TABLE DISCOGRAFICAS CASCADE CONSTRAINT;
DROP TABLE MANAGERS CASCADE CONSTRAINT;
DROP TABLE ESTUDIOS CASCADE CONSTRAINT;
DROP TABLE EMISORAS CASCADE CONSTRAINT;
DROP TABLE VINILOS CASCADE CONSTRAINT;
DROP TABLE MAQUETACIONES CASCADE CONSTRAINT;
DROP TABLE TEMAS CASCADE CONSTRAINT;
DROP TABLE MIEMBROS CASCADE CONSTRAINT;
DROP TABLE ALBUMES CASCADE CONSTRAINT;
DROP TABLE SINGLES CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE PEDIDOS CASCADE CONSTRAINT;
DROP TABLE TOPS CASCADE CONSTRAINT;

CREATE TABLE ARTISTAS
(nombre VARCHAR2(45),
nacionalidad VARCHAR2(15) NOT NULL,
idioma VARCHAR2(15) NOT NULL,
CONSTRAINT PK_ARTISTAS PRIMARY KEY (nombre));

CREATE TABLE DISCOGRAFICAS
(nombredf VARCHAR2(45),
tlf NUMBER(9) NOT NULL,
CONSTRAINT PK_DISCOGRAFICAS PRIMARY KEY (nombredf),
CONSTRAINT UK_DISCOGRAFICAS UNIQUE(tlf));

CREATE TABLE MANAGERS
(nombre VARCHAR2(35) NOT NULL,
ap1 VARCHAR2(30) NOT NULL,
ap2 VARCHAR2(30),
tlf NUMBER(9),
CONSTRAINT PK_MANAGERS PRIMARY KEY (tlf));

CREATE TABLE ESTUDIOS
(nombreest VARCHAR2(50),
direccionest VARCHAR2(80) NOT NULL,
nombrepers VARCHAR2(30) NOT NULL,
appers1 VARCHAR2(30) NOT NULL,
appers2 VARCHAR2(30),
CONSTRAINT PK_ESTUDIOS PRIMARY KEY (nombreest));

CREATE TABLE EMISORAS
(nombre VARCHAR2(45),
dir VARCHAR2(80) NOT NULL,
url VARCHAR2(40) NOT NULL,
email VARCHAR2(40) NOT NULL,
tlf NUMBER(9) NOT NULL,
CONSTRAINT PK_EMISORAS PRIMARY KEY (nombre));

CREATE TABLE VINILOS
(titdisco VARCHAR2(50) NOT NULL,
grupo VARCHAR2(45)NOT NULL,
velrot VARCHAR2(10) NOT NULL,
tamagu VARCHAR2(10) NOT NULL,
discografica VARCHAR2(45) NOT NULL,
fecha DATE NOT NULL,
isvn NUMBER(8),
managertlf NUMBER(9) NOT NULL,
color VARCHAR2 (15) NOT NULL,
CONSTRAINT PK_VINILOS PRIMARY KEY (isvn),
CONSTRAINT FK_VINILOS1 FOREIGN KEY (grupo) REFERENCES ARTISTAS ON DELETE CASCADE,
CONSTRAINT FK_VINILOS2 FOREIGN KEY (discografica) REFERENCES DISCOGRAFICAS,
CONSTRAINT FK_VINILOS3 FOREIGN KEY (managertlf) REFERENCES MANAGERS);

CREATE TABLE MAQUETACIONES
(empresa1 VARCHAR2(30),
dir1 VARCHAR(70) NOT NULL,
fotografo1 VARCHAR2 (70),
dibujante1 VARCHAR2(60),
maquetador1 VARCHAR2(50),
empresa2 VARCHAR2(30),
dir2 VARCHAR(80) NOT NULL,
fotografo2 VARCHAR2 (70),
dibujante2 VARCHAR2(60),
maquetador2 VARCHAR2(50),
isvn NUMBER(8),
CONSTRAINT PK_MAQUETACION PRIMARY KEY (empresa1, empresa2,isvn),
CONSTRAINT FK_MAQUETACION FOREIGN KEY (isvn) REFERENCES VINILOS); 

CREATE TABLE TEMAS 
(titulo VARCHAR2(50) NOT NULL,
cara VARCHAR2(20),
pista NUMBER(10),
duracion VARCHAR2(7) NOT NULL,
autor VARCHAR2(70)NOT NULL,
isvn NUMBER(8),
estudio VARCHAR2(50) NOT NULL,
CONSTRAINT PK_TEMAS PRIMARY KEY (isvn, cara, pista),
CONSTRAINT FK_TEMAS1 FOREIGN KEY (isvn) REFERENCES VINILOS ON DELETE CASCADE,
CONSTRAINT FK_TEMAS2 FOREIGN KEY (estudio) REFERENCES ESTUDIOS);

CREATE TABLE MIEMBROS 
(nombreart VARCHAR2(45),
rol VARCHAR2 (15),
grupo VARCHAR2(45),
CONSTRAINT PK_MIEMBROS PRIMARY KEY (nombreart, rol, grupo),
CONSTRAINT FK_MIEMBROS FOREIGN KEY (grupo) REFERENCES ARTISTAS);

CREATE TABLE ALBUMES
(coplanz NUMBER(7) NOT NULL,
coptot NUMBER(8) NOT NULL,
titdisco VARCHAR2(50) NOT NULL,
isvn NUMBER(8),
CONSTRAINT PK_ALBUMES PRIMARY KEY (isvn),
CONSTRAINT FK_ALBUMES FOREIGN KEY (isvn) REFERENCES VINILOS ON DELETE CASCADE);

CREATE TABLE SINGLES
(mejorp NUMBER (8),
tmpotop NUMBER (8),
isvn NUMBER(8),
CONSTRAINT PK_SINGLES PRIMARY KEY (isvn),
CONSTRAINT FK_SINGLES FOREIGN KEY (isvn) REFERENCES VINILOS ON DELETE CASCADE);

CREATE TABLE CLIENTES
(nombre VARCHAR2 (40) NOT NULL,
ap1 VARCHAR2 (30) NOT NULL,
ap2 VARCHAR2 (30),
dni NUMBER(8),
fechanac DATE NOT NULL,
tlf NUMBER(9) NOT NULL,
email VARCHAR2(50) NOT NULL,
cpostal VARCHAR2(90) NOT NULL,
CONSTRAINT PK_CLIENTES PRIMARY KEY (dni,tlf),
CONSTRAINT UK_CLIENTES UNIQUE(tlf,email));

CREATE TABLE PEDIDOS
(fechac DATE,
fechae DATE,
grupo VARCHAR2 (45) NOT NULL,
titdisco VARCHAR2 (50),
cliente NUMBER(8),
tlf NUMBER(9),
isvn NUMBER(8),
CONSTRAINT PK_PEDIDOS PRIMARY KEY (fechac, fechae, cliente, tlf, isvn),
CONSTRAINT FK_PEDIDOS1 FOREIGN KEY (isvn) REFERENCES VINILOS,
CONSTRAINT FK_PEDIDOS2 FOREIGN KEY (cliente, tlf) REFERENCES CLIENTES);

CREATE TABLE TOPS
(isvn NUMBER (8),
tema VARCHAR2(50) NOT NULL,
fecha DATE,
hora VARCHAR2(6),
emisora VARCHAR2 (45),
CONSTRAINT PK_TOPS PRIMARY KEY (isvn, fecha, hora, emisora),
CONSTRAINT FK_TOPS1 FOREIGN KEY (emisora) REFERENCES EMISORAS,
CONSTRAINT FK_TOPS2 FOREIGN KEY (isvn) REFERENCES VINILOS);
